name: StrudelJam Pipeline

on:
  workflow_dispatch:        # manual button
  push:                     # auto when you add prompt/model files
    branches: [ main ]
    paths:
      - 'public/prompts/**'
      - 'models/**'
      - 'scripts/**'
      - 'context.txt'

jobs:
  bench:
    runs-on: ubuntu-latest
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    # ----- install build-time deps -----
    - uses: actions/setup-node@v4
      with: 
        node-version: 18

    - name: Install Strudel packages locally
      run: npm ci

    - name: Install Python deps
      run: python -m pip install requests

    # ----- run the pipeline -----
    - name: Run new prompt/model combos
      run: python scripts/run_bench.py --only-new

    # ----- commit data back -----
    - name: Commit updated data
      run: |
        git config --global user.email "bot@github.com"
        git config --global user.name  "GitHub Actions"
        git add public/data/
        git commit -m "auto: update benchmark data" || echo "nothing to commit"
        git push

    # ----- generate prompt pages -----
    - name: Generate prompt pages
      run: |
        if [ -f public/data/index.json ]; then
          python scripts/generate_pages.py
        else
          echo "public/data/index.json not found, skipping page generation."
        fi

    # ----- DEBUG: List data directory before deploy -----
    - name: List data directory contents
      run: |
        echo "Listing public/data directory:"
        ls -R public/data || echo "public/data directory not found or empty"
        echo "Current working directory: $(pwd)"
        echo "Listing root of workspace:"
        ls -A .

    # ----- deploy GitHub Pages -----
    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
        # cname: your-domain.com  # optional: uncomment and add your custom domain 